<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tnt_jobs"
 *
 * Auto generated by Extension Builder 2014-07-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TNT JOBS',
	'description' => 'This Extension Deals with the job listing and applying for the jobs for the extension.',
	'category' => 'plugin',
	'author' => 'Hoja',
	'author_email' => 'hoja@tnt-graphics.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);