<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tnt_babygallery"
 *
 * Auto generated by Extension Builder 2014-07-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TNT BABY GALLERY',
	'description' => 'TNT BABY GALLERY is a custom TYPO3 6.2 FLUID EXT BASE Extension build for managing the baby gallery with different views on front end.',
	'category' => 'plugin',
	'author' => 'HOJA.M.A',
	'author_email' => 'hoja@tnt-graphics.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);